### ISSUE TITLE
As mentioned i tried using this app by shaking the phone ,but the app closed. Does the app work properly? Is there any modification that needs to be made ?

### ISSUE THREAD

**Issue by nidhiponnath** [PrabhuVinod/Women-Safety-App#1]

**Comment by PrabhuVinod** [comment]
This app was something I made a long time ago. So it may not support newer devices. Since this was first app I created to learn Android Development, it is very buggy. I am no longer maintaining or working this app.
If you want to use this, you should update the app version and recreate the app so that it will support newer(your) versions.
